MilliCar: ns3::millicar::MmWaveVehicularNetDevice Class Reference
ns3::millicar::MmWaveVehicularNetDevice Class Reference
#include "mmwave-vehicular-net-device.h"
Public Member Functions
MmWaveVehicularNetDevice (void)
Class constructor, it is not used.
MmWaveVehicularNetDevice (Ptr< MmWaveSidelinkPhy > phy, Ptr< MmWaveSidelinkMac > mac)
Class constructor.
virtual ~MmWaveVehicularNetDevice (void)
Class destructor.
void ActivateBearer (const uint8_t bearerId, const uint16_t destRnti, const Address &dest)
a logical channel with instances of PDCP/RLC layers is created and associated to a specific receiving device
virtual void AddLinkChangeCallback (Callback< void > callback)
virtual void DoDispose (void)
Destructor implementation.
virtual Address GetAddress (void) const
Returns MAC address associated to the NetDevice.
virtual Address GetBroadcast (void) const
virtual Ptr< Channel > GetChannel (void) const
virtual uint32_t GetIfIndex (void) const
virtual Ptr< MmWaveSidelinkMac > GetMac (void) const
Returns pointer to MAC.
virtual uint16_t GetMtu (void) const
Returns MTU associated to the NetDevice.
virtual Address GetMulticast (Ipv4Address multicastGroup) const
virtual Address GetMulticast (Ipv6Address addr) const
virtual Ptr< Node > GetNode (void) const
virtual Ptr< MmWaveSidelinkPhy > GetPhy (void) const
Returns pointer to PHY.
TypeId GetRlcType (std::string rlcType)
Returns valid LteRlc TypeId based on the parameter passed.
virtual bool IsBridge (void) const
virtual bool IsBroadcast (void) const
virtual bool IsLinkUp (void) const
virtual bool IsMulticast (void) const
virtual bool IsPointToPoint (void) const
virtual bool NeedsArp (void) const
void Receive (Ptr< Packet > p)
Packet forwarding to the MAC layer by calling DoTransmitPdu.
virtual bool Send (Ptr< Packet > packet, const Address &dest, uint16_t protocolNumber)
Send a packet to the vehicular stack.
virtual bool SendFrom (Ptr< Packet > packet, const Address &source, const Address &dest, uint16_t protocolNumber)
virtual void SetAddress (Address address)
Set MAC address associated to the NetDevice.
virtual void SetIfIndex (const uint32_t index)
virtual bool SetMtu (const uint16_t mtu)
Set MTU associated to the NetDevice.
virtual void SetNode (Ptr< Node > node)
virtual void SetPromiscReceiveCallback (PromiscReceiveCallback cb)
virtual void SetReceiveCallback (ReceiveCallback cb)
virtual bool SupportsSendFrom (void) const
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Protected Attributes
NetDevice::ReceiveCallback m_rxCallback
callback that is fired when a packet is received
Private Member Functions
uint8_t BidToLcid (const uint8_t bearerId) const
Return the LCID associated to a certain bearer.
Private Attributes
std::map< uint8_t, Ptr< SidelinkRadioBearerInfo > > m_bearerToInfoMap
map to store RLC and PDCP instances associated to a specific bearer ID
std::map< uint8_t, uint8_t > m_bid2lcid
map from the BID to a unique LCID
uint8_t m_bidCounter = 0
counter of bearer connections activated for a single UE
uint32_t m_ifIndex
uint8_t m_lcidCounter = 0
counter of logical channels created on this NetDevice
bool m_linkUp
boolean that indicates if the link is UP (true) or DOWN (false)
Ptr< MmWaveSidelinkMac > m_mac
pointer to the MAC instance to be associated to the NetDevice
Mac64Address m_macAddr
MAC address associated to the NetDevice.
uint16_t m_mtu
MTU associated to the NetDevice.
Ptr< Node > m_node
pointer to the node associated to the NetDevice
Ptr< MmWaveSidelinkPhy > m_phy
pointer to the PHY instance to be associated to the NetDevice
std::string m_rlcType
EpcTftClassifier m_tftClassifier
Detailed Description
Definition at line 50 of file mmwave-vehicular-net-device.h.
Constructor & Destructor Documentation
MmWaveVehicularNetDevice() [1/2]
ns3::millicar::MmWaveVehicularNetDevice::MmWaveVehicularNetDevice (void)
Class constructor, it is not used.
Definition at line 84 of file mmwave-vehicular-net-device.cc.
MmWaveVehicularNetDevice() [2/2]
ns3::millicar::MmWaveVehicularNetDevice::MmWaveVehicularNetDevice (Ptr< MmWaveSidelinkPhy > phy, Ptr< MmWaveSidelinkMac > mac)
Class constructor.
Parameters
phy pointer to the PHY
mac pointer to the MAC
Definition at line 89 of file mmwave-vehicular-net-device.cc.
~MmWaveVehicularNetDevice()
ns3::millicar::MmWaveVehicularNetDevice::~MmWaveVehicularNetDevice (void) virtual
Class destructor.
Definition at line 96 of file mmwave-vehicular-net-device.cc.
Member Function Documentation
ActivateBearer()
void ns3::millicar::MmWaveVehicularNetDevice::ActivateBearer (const uint8_t bearerId, const uint16_t destRnti, const Address & dest)
a logical channel with instances of PDCP/RLC layers is created and associated to a specific receiving device
Parameters
bearerId identifier of the tunnel between two devices
destRnti the rnti of the destination
dest IP destination address
Definition at line 286 of file mmwave-vehicular-net-device.cc.
References ns3::millicar::PdcpSpecificSidelinkPdcpSapUser::PdcpSpecificSidelinkPdcpSapUser().
AddLinkChangeCallback()
void ns3::millicar::MmWaveVehicularNetDevice::AddLinkChangeCallback (Callback< void > callback) virtual
Definition at line 132 of file mmwave-vehicular-net-device.cc.
BidToLcid()
uint8_t ns3::millicar::MmWaveVehicularNetDevice::BidToLcid (const uint8_t bearerId) const private
Return the LCID associated to a certain bearer.
Parameters
bearerId the bearer
Returns
the logical channel ID
Definition at line 405 of file mmwave-vehicular-net-device.cc.
DoDispose()
void ns3::millicar::MmWaveVehicularNetDevice::DoDispose (void) virtual
Destructor implementation.
Definition at line 102 of file mmwave-vehicular-net-device.cc.
GetAddress()
Address ns3::millicar::MmWaveVehicularNetDevice::GetAddress (void) const virtual
Returns MAC address associated to the NetDevice.
Definition at line 231 of file mmwave-vehicular-net-device.cc.
GetBroadcast()
Address ns3::millicar::MmWaveVehicularNetDevice::GetBroadcast (void) const virtual
Definition at line 143 of file mmwave-vehicular-net-device.cc.
GetChannel()
Ptr< Channel > ns3::millicar::MmWaveVehicularNetDevice::GetChannel (void) const virtual
Definition at line 120 of file mmwave-vehicular-net-device.cc.
GetIfIndex()
uint32_t ns3::millicar::MmWaveVehicularNetDevice::GetIfIndex (void) const virtual
Definition at line 114 of file mmwave-vehicular-net-device.cc.
GetMac()
Ptr< MmWaveSidelinkMac > ns3::millicar::MmWaveVehicularNetDevice::GetMac (void) const virtual
Returns pointer to MAC.
Definition at line 238 of file mmwave-vehicular-net-device.cc.
GetMtu()
uint16_t ns3::millicar::MmWaveVehicularNetDevice::GetMtu (void) const virtual
Returns MTU associated to the NetDevice.
Definition at line 259 of file mmwave-vehicular-net-device.cc.
Referenced by GetTypeId().
GetMulticast() [1/2]
Address ns3::millicar::MmWaveVehicularNetDevice::GetMulticast (Ipv4Address multicastGroup) const virtual
Definition at line 155 of file mmwave-vehicular-net-device.cc.
GetMulticast() [2/2]
Address ns3::millicar::MmWaveVehicularNetDevice::GetMulticast (Ipv6Address addr) const virtual
Definition at line 198 of file mmwave-vehicular-net-device.cc.
GetNode()
Ptr< Node > ns3::millicar::MmWaveVehicularNetDevice::GetNode (void) const virtual
Definition at line 180 of file mmwave-vehicular-net-device.cc.
GetPhy()
Ptr< MmWaveSidelinkPhy > ns3::millicar::MmWaveVehicularNetDevice::GetPhy (void) const virtual
Returns pointer to PHY.
Definition at line 245 of file mmwave-vehicular-net-device.cc.
GetRlcType()
TypeId ns3::millicar::MmWaveVehicularNetDevice::GetRlcType (std::string rlcType)
Returns valid LteRlc TypeId based on the parameter passed.
Parameters
rlcType string representing the selected RLC type
Returns
the type id of the proper RLC class
Definition at line 265 of file mmwave-vehicular-net-device.cc.
GetTypeId()
TypeId ns3::millicar::MmWaveVehicularNetDevice::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 59 of file mmwave-vehicular-net-device.cc.
References GetMtu(), m_bearerToInfoMap, m_rlcType, and SetMtu().
IsBridge()
bool ns3::millicar::MmWaveVehicularNetDevice::IsBridge (void) const virtual
Definition at line 161 of file mmwave-vehicular-net-device.cc.
IsBroadcast()
bool ns3::millicar::MmWaveVehicularNetDevice::IsBroadcast (void) const virtual
Definition at line 137 of file mmwave-vehicular-net-device.cc.
IsLinkUp()
bool ns3::millicar::MmWaveVehicularNetDevice::IsLinkUp (void) const virtual
Definition at line 126 of file mmwave-vehicular-net-device.cc.
IsMulticast()
bool ns3::millicar::MmWaveVehicularNetDevice::IsMulticast (void) const virtual
Definition at line 149 of file mmwave-vehicular-net-device.cc.
IsPointToPoint()
bool ns3::millicar::MmWaveVehicularNetDevice::IsPointToPoint (void) const virtual
Definition at line 167 of file mmwave-vehicular-net-device.cc.
NeedsArp()
bool ns3::millicar::MmWaveVehicularNetDevice::NeedsArp (void) const virtual
Definition at line 192 of file mmwave-vehicular-net-device.cc.
Receive()
void ns3::millicar::MmWaveVehicularNetDevice::Receive (Ptr< Packet > p)
Packet forwarding to the MAC layer by calling DoTransmitPdu.
Parameters
p packet to be used to fire the callbacks
Definition at line 351 of file mmwave-vehicular-net-device.cc.
Referenced by ns3::millicar::MmWaveVehicularHelper::InstallSingleMmWaveVehicularNetDevice().
Send()
bool ns3::millicar::MmWaveVehicularNetDevice::Send (Ptr< Packet > packet, const Address & dest, uint16_t protocolNumber) virtual
Send a packet to the vehicular stack.
Parameters
address MAC address of the destination device
protocolNumber identifies if NetDevice is using IPv4 or IPv6
Definition at line 375 of file mmwave-vehicular-net-device.cc.
SendFrom()
bool ns3::millicar::MmWaveVehicularNetDevice::SendFrom (Ptr< Packet > packet, const Address & source, const Address & dest, uint16_t protocolNumber) virtual
Definition at line 173 of file mmwave-vehicular-net-device.cc.
SetAddress()
void ns3::millicar::MmWaveVehicularNetDevice::SetAddress (Address address) virtual
Set MAC address associated to the NetDevice.
Parameters
address MAC address
Definition at line 224 of file mmwave-vehicular-net-device.cc.
SetIfIndex()
void ns3::millicar::MmWaveVehicularNetDevice::SetIfIndex (const uint32_t index) virtual
Definition at line 108 of file mmwave-vehicular-net-device.cc.
SetMtu()
bool ns3::millicar::MmWaveVehicularNetDevice::SetMtu (const uint16_t mtu) virtual
Set MTU associated to the NetDevice.
Parameters
mtu size of the Maximum Transmission Unit
Definition at line 252 of file mmwave-vehicular-net-device.cc.
Referenced by GetTypeId().
SetNode()
void ns3::millicar::MmWaveVehicularNetDevice::SetNode (Ptr< Node > node) virtual
Definition at line 186 of file mmwave-vehicular-net-device.cc.
SetPromiscReceiveCallback()
void ns3::millicar::MmWaveVehicularNetDevice::SetPromiscReceiveCallback (PromiscReceiveCallback cb) virtual
Definition at line 212 of file mmwave-vehicular-net-device.cc.
SetReceiveCallback()
void ns3::millicar::MmWaveVehicularNetDevice::SetReceiveCallback (ReceiveCallback cb) virtual
Definition at line 205 of file mmwave-vehicular-net-device.cc.
SupportsSendFrom()
bool ns3::millicar::MmWaveVehicularNetDevice::SupportsSendFrom (void) const virtual
Definition at line 218 of file mmwave-vehicular-net-device.cc.
Member Data Documentation
m_bearerToInfoMap
std::map<uint8_t, Ptr<SidelinkRadioBearerInfo> > ns3::millicar::MmWaveVehicularNetDevice::m_bearerToInfoMap private
map to store RLC and PDCP instances associated to a specific bearer ID
Definition at line 189 of file mmwave-vehicular-net-device.h.
Referenced by GetTypeId().
m_bid2lcid
std::map<uint8_t,uint8_t> ns3::millicar::MmWaveVehicularNetDevice::m_bid2lcid private
map from the BID to a unique LCID
Definition at line 194 of file mmwave-vehicular-net-device.h.
m_bidCounter
uint8_t ns3::millicar::MmWaveVehicularNetDevice::m_bidCounter = 0 private
counter of bearer connections activated for a single UE
Definition at line 192 of file mmwave-vehicular-net-device.h.
m_ifIndex
uint32_t ns3::millicar::MmWaveVehicularNetDevice::m_ifIndex private
Definition at line 195 of file mmwave-vehicular-net-device.h.
m_lcidCounter
uint8_t ns3::millicar::MmWaveVehicularNetDevice::m_lcidCounter = 0 private
counter of logical channels created on this NetDevice
Definition at line 193 of file mmwave-vehicular-net-device.h.
m_linkUp
bool ns3::millicar::MmWaveVehicularNetDevice::m_linkUp private
boolean that indicates if the link is UP (true) or DOWN (false)
Definition at line 196 of file mmwave-vehicular-net-device.h.
m_mac
Ptr<MmWaveSidelinkMac> ns3::millicar::MmWaveVehicularNetDevice::m_mac private
pointer to the MAC instance to be associated to the NetDevice
Definition at line 187 of file mmwave-vehicular-net-device.h.
m_macAddr
Mac64Address ns3::millicar::MmWaveVehicularNetDevice::m_macAddr private
MAC address associated to the NetDevice.
Definition at line 190 of file mmwave-vehicular-net-device.h.
m_mtu
uint16_t ns3::millicar::MmWaveVehicularNetDevice::m_mtu mutable private
MTU associated to the NetDevice.
Definition at line 191 of file mmwave-vehicular-net-device.h.
m_node
Ptr<Node> ns3::millicar::MmWaveVehicularNetDevice::m_node private
pointer to the node associated to the NetDevice
Definition at line 197 of file mmwave-vehicular-net-device.h.
m_phy
Ptr<MmWaveSidelinkPhy> ns3::millicar::MmWaveVehicularNetDevice::m_phy private
pointer to the PHY instance to be associated to the NetDevice
Definition at line 188 of file mmwave-vehicular-net-device.h.
m_rlcType
std::string ns3::millicar::MmWaveVehicularNetDevice::m_rlcType private
Definition at line 199 of file mmwave-vehicular-net-device.h.
Referenced by GetTypeId().
m_rxCallback
NetDevice::ReceiveCallback ns3::millicar::MmWaveVehicularNetDevice::m_rxCallback protected
callback that is fired when a packet is received
Definition at line 184 of file mmwave-vehicular-net-device.h.
m_tftClassifier
EpcTftClassifier ns3::millicar::MmWaveVehicularNetDevice::m_tftClassifier private
Definition at line 198 of file mmwave-vehicular-net-device.h.
The documentation for this class was generated from the following files:
model/mmwave-vehicular-net-device.h
model/mmwave-vehicular-net-device.cc