MilliCar: MmWaveVehicularRateTestCase Class Reference
MmWaveVehicularRateTestCase Class Reference
This is a test to check if the designed vehicular stack (MAC and PHY) is able to run on a basic scenario: two vehicle moving at constant velocity and constant distance.
Public Member Functions
MmWaveVehicularRateTestCase ()
Constructor.
virtual ~MmWaveVehicularRateTestCase ()
Destructor.
virtual void DoRun (void)
This method run the test.
void StartTest (uint8_t mcs)
Private Member Functions
void Rx (Ptr< const Packet > p)
Callback sink fired when the rx receives a packet.
void Tx (Ptr< const Packet > p)
Callback sink fired when the tx transmits a packet.
Private Attributes
Time g_firstReceived
timestamp of the first time a packet is received on a single test-case
Time g_lastReceived
timestamp of the last received packet on a single test-case
uint32_t g_rxPackets
total number of received packets on a single test-case
uint32_t g_txPackets
total number of transmitted packets on a single test-case
Detailed Description
This is a test to check if the designed vehicular stack (MAC and PHY) is able to run on a basic scenario: two vehicle moving at constant velocity and constant distance.
The distance increases among different tests of the suite.
Definition at line 44 of file mmwave-vehicular-rate-test.cc.
Constructor & Destructor Documentation
MmWaveVehicularRateTestCase()
MmWaveVehicularRateTestCase::MmWaveVehicularRateTestCase ()
Constructor.
Definition at line 86 of file mmwave-vehicular-rate-test.cc.
~MmWaveVehicularRateTestCase()
MmWaveVehicularRateTestCase::~MmWaveVehicularRateTestCase () virtual
Destructor.
Definition at line 91 of file mmwave-vehicular-rate-test.cc.
Member Function Documentation
DoRun()
void MmWaveVehicularRateTestCase::DoRun (void) virtual
This method run the test.
Definition at line 119 of file mmwave-vehicular-rate-test.cc.
References g_rxPackets, g_txPackets, and StartTest().
Rx()
void MmWaveVehicularRateTestCase::Rx (Ptr< const Packet > p) private
Callback sink fired when the rx receives a packet.
Parameters
p received packet
Definition at line 103 of file mmwave-vehicular-rate-test.cc.
References g_firstReceived, g_lastReceived, and g_rxPackets.
Referenced by StartTest().
StartTest()
void MmWaveVehicularRateTestCase::StartTest (uint8_t mcs)
Definition at line 136 of file mmwave-vehicular-rate-test.cc.
References g_firstReceived, g_lastReceived, g_rxPackets, g_txPackets, Rx(), and Tx().
Referenced by DoRun().
Tx()
void MmWaveVehicularRateTestCase::Tx (Ptr< const Packet > p) private
Callback sink fired when the tx transmits a packet.
Parameters
p transmitted packet
Definition at line 96 of file mmwave-vehicular-rate-test.cc.
References g_txPackets.
Referenced by StartTest().
Member Data Documentation
g_firstReceived
Time MmWaveVehicularRateTestCase::g_firstReceived private
timestamp of the first time a packet is received on a single test-case
Definition at line 81 of file mmwave-vehicular-rate-test.cc.
Referenced by Rx(), and StartTest().
g_lastReceived
Time MmWaveVehicularRateTestCase::g_lastReceived private
timestamp of the last received packet on a single test-case
Definition at line 82 of file mmwave-vehicular-rate-test.cc.
Referenced by Rx(), and StartTest().
g_rxPackets
uint32_t MmWaveVehicularRateTestCase::g_rxPackets private
total number of received packets on a single test-case
Definition at line 78 of file mmwave-vehicular-rate-test.cc.
Referenced by DoRun(), Rx(), and StartTest().
g_txPackets
uint32_t MmWaveVehicularRateTestCase::g_txPackets private
total number of transmitted packets on a single test-case
Definition at line 79 of file mmwave-vehicular-rate-test.cc.
Referenced by DoRun(), StartTest(), and Tx().
The documentation for this class was generated from the following file:
test/mmwave-vehicular-rate-test.cc