MilliCar: ns3::millicar::MmWaveVehicularHelper Class Reference
ns3::millicar::MmWaveVehicularHelper Class Reference
This class is used for the creation of MmWaveVehicularNetDevices and their configuration.
#include "mmwave-vehicular-helper.h"
Public Types
enum SchedulingPatternOption_t { DEFAULT = 1, OPTIMIZED = 2 }
Identifies the supported scheduling pattern policies.
Public Member Functions
MmWaveVehicularHelper (void)
Constructor.
virtual ~MmWaveVehicularHelper (void)
Destructor.
std::vector< uint16_t > CreateSchedulingPattern (NetDeviceContainer devices)
Configure the scheduling pattern for a specific group of devices.
Ptr< mmwave::MmWavePhyMacCommon > GetConfigurationParameters () const
Retrieve pointer to the object that lists all the configuration parameters.
SchedulingPatternOption_t GetSchedulingPatternOptionType () const
Returns the adopted scheduling pattern policy.
NetDeviceContainer InstallMmWaveVehicularNetDevices (NodeContainer nodes)
Install a MmWaveVehicularNetDevice on each node in the container.
void PairDevices (NetDeviceContainer devices)
Associate the devices in the container.
void SetConfigurationParameters (Ptr< mmwave::MmWavePhyMacCommon > conf)
Set the configuration parameters.
void SetNumerology (uint8_t index)
Configure the numerology index.
void SetPropagationDelayModelType (std::string pdm)
Set the propagation delay model type.
void SetPropagationLossModelType (std::string plm)
Set the propagation loss model type.
void SetSchedulingPatternOptionType (SchedulingPatternOption_t spo)
Set the scheduling pattern option type.
void SetSpectrumPropagationLossModelType (std::string splm)
Set the spectrum propagation loss model type.
Static Public Member Functions
static TypeId GetTypeId (void)
Protected Member Functions
virtual void DoInitialize (void) override
Private Member Functions
Ptr< MmWaveVehicularNetDevice > InstallSingleMmWaveVehicularNetDevice (Ptr< Node > n, uint16_t rnti)
Install a MmWaveVehicularNetDevice on the node.
Private Attributes
double m_bandwidth
system bandwidth
Ptr< SpectrumChannel > m_channel
the SpectrumChannel
uint8_t m_numerologyIndex
numerology index
Ptr< mmwave::MmWavePhyMacCommon > m_phyMacConfig
the configuration parameters
Ptr< MmWaveVehicularTracesHelper > m_phyTraceHelper
Ptr to an helper for the physical layer traces.
std::string m_propagationDelayModelType
the type id of the delay model to be used
std::string m_propagationLossModelType
the type id of the propagation loss model to be used
uint16_t m_rntiCounter
a counter to set the RNTIs
SchedulingPatternOption_t m_schedulingOpt
the type of scheduling pattern policy to be adopted
std::string m_spectrumPropagationLossModelType
the type id of the spectrum propagation loss model to be used
Detailed Description
This class is used for the creation of MmWaveVehicularNetDevices and their configuration.
Definition at line 41 of file mmwave-vehicular-helper.h.
Member Enumeration Documentation
SchedulingPatternOption_t
enum ns3::millicar::MmWaveVehicularHelper::SchedulingPatternOption_t
Identifies the supported scheduling pattern policies.
Enumerator
DEFAULT
OPTIMIZED
Definition at line 116 of file mmwave-vehicular-helper.h.
Constructor & Destructor Documentation
MmWaveVehicularHelper()
ns3::millicar::MmWaveVehicularHelper::MmWaveVehicularHelper (void)
Constructor.
Definition at line 39 of file mmwave-vehicular-helper.cc.
~MmWaveVehicularHelper()
ns3::millicar::MmWaveVehicularHelper::~MmWaveVehicularHelper (void) virtual
Destructor.
Definition at line 45 of file mmwave-vehicular-helper.cc.
Member Function Documentation
CreateSchedulingPattern()
std::vector< uint16_t > ns3::millicar::MmWaveVehicularHelper::CreateSchedulingPattern (NetDeviceContainer devices)
Configure the scheduling pattern for a specific group of devices.
Parameters
devices the NetDeviceContainer with the devices
Returns
a vector of integers representing the scheduling pattern
Definition at line 315 of file mmwave-vehicular-helper.cc.
References DEFAULT, m_phyMacConfig, m_schedulingOpt, and OPTIMIZED.
Referenced by PairDevices().
DoInitialize()
void ns3::millicar::MmWaveVehicularHelper::DoInitialize (void) override protected virtual
Definition at line 105 of file mmwave-vehicular-helper.cc.
References m_bandwidth, m_channel, m_numerologyIndex, m_phyMacConfig, m_propagationDelayModelType, m_propagationLossModelType, m_rntiCounter, and m_spectrumPropagationLossModelType.
GetConfigurationParameters()
Ptr< mmwave::MmWavePhyMacCommon > ns3::millicar::MmWaveVehicularHelper::GetConfigurationParameters () const
Retrieve pointer to the object that lists all the configuration parameters.
Returns
a pointer to a MmWavePhyMacCommon object
Definition at line 162 of file mmwave-vehicular-helper.cc.
References m_phyMacConfig.
GetSchedulingPatternOptionType()
MmWaveVehicularHelper::SchedulingPatternOption_t ns3::millicar::MmWaveVehicularHelper::GetSchedulingPatternOptionType () const
Returns the adopted scheduling pattern policy.
Returns
the adopted scheduling pattern policy
Definition at line 412 of file mmwave-vehicular-helper.cc.
References m_schedulingOpt.
Referenced by GetTypeId().
GetTypeId()
TypeId ns3::millicar::MmWaveVehicularHelper::GetTypeId (void) static
Definition at line 51 of file mmwave-vehicular-helper.cc.
References DEFAULT, GetSchedulingPatternOptionType(), m_bandwidth, OPTIMIZED, SetNumerology(), SetPropagationDelayModelType(), SetPropagationLossModelType(), SetSchedulingPatternOptionType(), and SetSpectrumPropagationLossModelType().
InstallMmWaveVehicularNetDevices()
NetDeviceContainer ns3::millicar::MmWaveVehicularHelper::InstallMmWaveVehicularNetDevices (NodeContainer nodes)
Install a MmWaveVehicularNetDevice on each node in the container.
Parameters
nodes the node container
Returns
a NetDeviceContainer containing the installed devices
Definition at line 176 of file mmwave-vehicular-helper.cc.
References InstallSingleMmWaveVehicularNetDevice(), and m_rntiCounter.
InstallSingleMmWaveVehicularNetDevice()
Ptr< MmWaveVehicularNetDevice > ns3::millicar::MmWaveVehicularHelper::InstallSingleMmWaveVehicularNetDevice (Ptr< Node > n, uint16_t rnti) private
Install a MmWaveVehicularNetDevice on the node.
Parameters
n the node
rnti the RNTI
Returns
pointer to the installed NetDevice
Definition at line 200 of file mmwave-vehicular-helper.cc.
References ns3::millicar::MmWaveSidelinkPhy::GenerateSinrReport(), m_channel, m_phyMacConfig, m_phyTraceHelper, ns3::millicar::MmWaveVehicularTracesHelper::McsSinrCallback(), ns3::millicar::MmWaveSidelinkPhy::Receive(), ns3::millicar::MmWaveVehicularNetDevice::Receive(), and ns3::millicar::MmWaveSidelinkSpectrumPhy::UpdateSinrPerceived().
Referenced by InstallMmWaveVehicularNetDevices().
PairDevices()
void ns3::millicar::MmWaveVehicularHelper::PairDevices (NetDeviceContainer devices)
Associate the devices in the container.
Parameters
devices the NetDeviceContainer with the devices
Definition at line 264 of file mmwave-vehicular-helper.cc.
References CreateSchedulingPattern().
SetConfigurationParameters()
void ns3::millicar::MmWaveVehicularHelper::SetConfigurationParameters (Ptr< mmwave::MmWavePhyMacCommon > conf)
Set the configuration parameters.
Parameters
conf pointer to mmwave::MmWavePhyMacCommon
Definition at line 154 of file mmwave-vehicular-helper.cc.
References m_phyMacConfig, and m_rntiCounter.
SetNumerology()
void ns3::millicar::MmWaveVehicularHelper::SetNumerology (uint8_t index)
Configure the numerology index.
Parameters
index numerology index, used to define PHY layer parameters
Definition at line 169 of file mmwave-vehicular-helper.cc.
References m_numerologyIndex.
Referenced by GetTypeId().
SetPropagationDelayModelType()
void ns3::millicar::MmWaveVehicularHelper::SetPropagationDelayModelType (std::string pdm)
Set the propagation delay model type.
Parameters
pdm the type id of the propagation delay model to use
Definition at line 398 of file mmwave-vehicular-helper.cc.
References m_propagationDelayModelType.
Referenced by GetTypeId().
SetPropagationLossModelType()
void ns3::millicar::MmWaveVehicularHelper::SetPropagationLossModelType (std::string plm)
Set the propagation loss model type.
Parameters
plm the type id of the propagation loss model to use
Definition at line 384 of file mmwave-vehicular-helper.cc.
References m_propagationLossModelType.
Referenced by GetTypeId().
SetSchedulingPatternOptionType()
void ns3::millicar::MmWaveVehicularHelper::SetSchedulingPatternOptionType (SchedulingPatternOption_t spo)
Set the scheduling pattern option type.
Parameters
spo the enum representing the scheduling pattern policy to be adopted
Definition at line 405 of file mmwave-vehicular-helper.cc.
References m_schedulingOpt.
Referenced by GetTypeId().
SetSpectrumPropagationLossModelType()
void ns3::millicar::MmWaveVehicularHelper::SetSpectrumPropagationLossModelType (std::string splm)
Set the spectrum propagation loss model type.
Parameters
splm the type id of the spectrum propagation loss model to use
Definition at line 391 of file mmwave-vehicular-helper.cc.
References m_spectrumPropagationLossModelType.
Referenced by GetTypeId().
Member Data Documentation
m_bandwidth
double ns3::millicar::MmWaveVehicularHelper::m_bandwidth private
system bandwidth
Definition at line 148 of file mmwave-vehicular-helper.h.
Referenced by DoInitialize(), and GetTypeId().
m_channel
Ptr<SpectrumChannel> ns3::millicar::MmWaveVehicularHelper::m_channel private
the SpectrumChannel
Definition at line 144 of file mmwave-vehicular-helper.h.
Referenced by DoInitialize(), and InstallSingleMmWaveVehicularNetDevice().
m_numerologyIndex
uint8_t ns3::millicar::MmWaveVehicularHelper::m_numerologyIndex private
numerology index
Definition at line 147 of file mmwave-vehicular-helper.h.
Referenced by DoInitialize(), and SetNumerology().
m_phyMacConfig
Ptr<mmwave::MmWavePhyMacCommon> ns3::millicar::MmWaveVehicularHelper::m_phyMacConfig private
the configuration parameters
Definition at line 145 of file mmwave-vehicular-helper.h.
Referenced by CreateSchedulingPattern(), DoInitialize(), GetConfigurationParameters(), InstallSingleMmWaveVehicularNetDevice(), and SetConfigurationParameters().
m_phyTraceHelper
Ptr<MmWaveVehicularTracesHelper> ns3::millicar::MmWaveVehicularHelper::m_phyTraceHelper private
Ptr to an helper for the physical layer traces.
Definition at line 154 of file mmwave-vehicular-helper.h.
Referenced by InstallSingleMmWaveVehicularNetDevice().
m_propagationDelayModelType
std::string ns3::millicar::MmWaveVehicularHelper::m_propagationDelayModelType private
the type id of the delay model to be used
Definition at line 151 of file mmwave-vehicular-helper.h.
Referenced by DoInitialize(), and SetPropagationDelayModelType().
m_propagationLossModelType
std::string ns3::millicar::MmWaveVehicularHelper::m_propagationLossModelType private
the type id of the propagation loss model to be used
Definition at line 149 of file mmwave-vehicular-helper.h.
Referenced by DoInitialize(), and SetPropagationLossModelType().
m_rntiCounter
uint16_t ns3::millicar::MmWaveVehicularHelper::m_rntiCounter private
a counter to set the RNTIs
Definition at line 146 of file mmwave-vehicular-helper.h.
Referenced by DoInitialize(), InstallMmWaveVehicularNetDevices(), and SetConfigurationParameters().
m_schedulingOpt
SchedulingPatternOption_t ns3::millicar::MmWaveVehicularHelper::m_schedulingOpt private
the type of scheduling pattern policy to be adopted
Definition at line 152 of file mmwave-vehicular-helper.h.
Referenced by CreateSchedulingPattern(), GetSchedulingPatternOptionType(), and SetSchedulingPatternOptionType().
m_spectrumPropagationLossModelType
std::string ns3::millicar::MmWaveVehicularHelper::m_spectrumPropagationLossModelType private
the type id of the spectrum propagation loss model to be used
Definition at line 150 of file mmwave-vehicular-helper.h.
Referenced by DoInitialize(), and SetSpectrumPropagationLossModelType().
The documentation for this class was generated from the following files:
helper/mmwave-vehicular-helper.h
helper/mmwave-vehicular-helper.cc