MilliCar: ns3::millicar::MmWaveVehicularSpectrumPropagationLossModel Class Reference
ns3::millicar::MmWaveVehicularSpectrumPropagationLossModel Class Reference
This class implements the fading computation of the 3GPP TR 38.900 channel model and performs the beamforming gain computation.
#include "mmwave-vehicular-spectrum-propagation-loss-model.h"
Public Member Functions
MmWaveVehicularSpectrumPropagationLossModel ()
Constructor.
virtual ~MmWaveVehicularSpectrumPropagationLossModel ()
Destructor.
void AddDevice (Ptr< NetDevice >, Ptr< MmWaveVehicularAntennaArrayModel >)
Add a device.
void DoDispose ()
double GetFrequency (void) const
void SetFrequency (double freq)
void SetPathlossModel (Ptr< PropagationLossModel > pathloss)
Set the pathloss model associated to this class.
Static Public Member Functions
static TypeId GetTypeId (void)
Private Member Functions
doubleVector_t CalAttenuationOfBlockage (Ptr< Params3gpp > params, doubleVector_t clusterAOA, doubleVector_t clusterZOA) const
Ptr< SpectrumValue > CalBeamformingGain (Ptr< const SpectrumValue > txPsd, Ptr< Params3gpp > params, complexVector_t longTerm, Vector rxSpeed, Vector txSpeed) const
Compute the BF gain, apply frequency selectivity by phase-shifting with the cluster delays and scale the txPsd to get the rxPsd.
complexVector_t CalLongTerm (Ptr< Params3gpp > params) const
Compute and return the long term fading params in order to decrease the computational load.
void DeleteChannel (Ptr< const MobilityModel > a, Ptr< const MobilityModel > b) const
Delete the m_channel entry associated to the Params3gpp object of pair (a,b) but keep the other parameters, so that the spatial consistency procedure can be used.
Ptr< SpectrumValue > DoCalcRxPowerSpectralDensity (Ptr< const SpectrumValue > txPsd, Ptr< const MobilityModel > a, Ptr< const MobilityModel > b) const
Inherited from SpectrumPropagationLossModel, it returns the PSD at the receiver.
Ptr< ParamsTable > Get3gppTable (char condition, bool o2i, double hBS, double hUT, double distance2D) const
Returns the ParamsTable with the parameters of TR 38.900 Table 7.5-6 that apply to a certain scenario.
Ptr< Params3gpp > GetNewChannel (Ptr< ParamsTable > table3gpp, Vector locUT, char condition, bool o2i, Ptr< MmWaveVehicularAntennaArrayModel > txAntenna, Ptr< MmWaveVehicularAntennaArrayModel > rxAntenna, uint16_t *txAntennaNum, uint16_t *rxAntennaNum, Angles &rxAngle, Angles &txAngle, Vector speed, double dis2D, double dis3D) const
Get a new realization of the channel.
double GetOxygenLoss (double frequency, double dist3D, double tau, double tauDelta) const
Returns the loss associated to the oxygen absorption as described in p.
double GetSystemBandwidth () const
Returns the bandwidth used in a scenario.
Ptr< Params3gpp > UpdateChannel (Ptr< Params3gpp > params3gpp, Ptr< ParamsTable > table3gpp, Ptr< MmWaveVehicularAntennaArrayModel > txAntenna, Ptr< MmWaveVehicularAntennaArrayModel > rxAntenna, uint16_t *txAntennaNum, uint16_t *rxAntennaNum, Angles &rxAngle, Angles &txAngle) const
Update the channel realization with procedure A of TR 38.900 Sec 7.6.3.2 for the spatial consistency.
Private Attributes
Ptr< PropagationLossModel > m_3gppPathloss
bool m_blockage
double m_blockerSpeed
std::map< key_t, Ptr< Params3gpp > > m_channelMap
std::map< Ptr< NetDevice >, Ptr< MmWaveVehicularAntennaArrayModel > > m_deviceAntennaMap
Ptr< ExponentialRandomVariable > m_expRv
double m_frequency
bool m_interferenceOrDataMode
Ptr< NormalRandomVariable > m_normalRv
Ptr< NormalRandomVariable > m_normalRvBlockage
uint16_t m_numNonSelfBloking
bool m_o2i
bool m_oxygenAbsorption
bool m_portraitMode
std::string m_scenario
Ptr< ParamsTable > m_table3gpp
Ptr< UniformRandomVariable > m_uniformRv
Ptr< UniformRandomVariable > m_uniformRvBlockage
Time m_updatePeriod
Detailed Description
This class implements the fading computation of the 3GPP TR 38.900 channel model and performs the beamforming gain computation.
It implements the SpectrumPropagationLossModel interface
Definition at line 169 of file mmwave-vehicular-spectrum-propagation-loss-model.h.
Constructor & Destructor Documentation
MmWaveVehicularSpectrumPropagationLossModel()
ns3::millicar::MmWaveVehicularSpectrumPropagationLossModel::MmWaveVehicularSpectrumPropagationLossModel ()
Constructor.
Definition at line 95 of file mmwave-vehicular-spectrum-propagation-loss-model.cc.
References m_expRv, m_normalRv, m_normalRvBlockage, m_uniformRv, and m_uniformRvBlockage.
~MmWaveVehicularSpectrumPropagationLossModel()
ns3::millicar::MmWaveVehicularSpectrumPropagationLossModel::~MmWaveVehicularSpectrumPropagationLossModel () virtual
Destructor.
Definition at line 159 of file mmwave-vehicular-spectrum-propagation-loss-model.cc.
Member Function Documentation
AddDevice()
void ns3::millicar::MmWaveVehicularSpectrumPropagationLossModel::AddDevice (Ptr< NetDevice > dev, Ptr< MmWaveVehicularAntennaArrayModel > antenna)
Add a device.
Parameters
a pointer to the NetDevice
a pointer to the associated MmWaveVehicularAntennaArrayModel
Definition at line 171 of file mmwave-vehicular-spectrum-propagation-loss-model.cc.
References m_deviceAntennaMap.
CalAttenuationOfBlockage()
doubleVector_t ns3::millicar::MmWaveVehicularSpectrumPropagationLossModel::CalAttenuationOfBlockage (Ptr< Params3gpp > params, doubleVector_t clusterAOA, doubleVector_t clusterZOA) const private
Definition at line 2269 of file mmwave-vehicular-spectrum-propagation-loss-model.cc.
References m_blockerSpeed, m_frequency, m_normalRvBlockage, m_numNonSelfBloking, m_portraitMode, m_scenario, m_uniformRvBlockage, PHI_INDEX, R_INDEX, THETA_INDEX, X_INDEX, and Y_INDEX.
Referenced by GetNewChannel(), and UpdateChannel().
CalBeamformingGain()
Ptr< SpectrumValue > ns3::millicar::MmWaveVehicularSpectrumPropagationLossModel::CalBeamformingGain (Ptr< const SpectrumValue > txPsd, Ptr< Params3gpp > params, complexVector_t longTerm, Vector rxSpeed, Vector txSpeed) const private
Compute the BF gain, apply frequency selectivity by phase-shifting with the cluster delays and scale the txPsd to get the rxPsd.
Parameters
the tx PSD
the channel realizationin as a Params3gpp object
the longTerm component (i.e., with the BF vectors already applied)
the speed of the receivers
the speed of the transmitter (for example in case of vehicular communication)
Returns
the rx PSD
Definition at line 382 of file mmwave-vehicular-spectrum-propagation-loss-model.cc.
References AOA_INDEX, AOD_INDEX, GetOxygenLoss(), m_frequency, m_oxygenAbsorption, m_scenario, m_uniformRv, ZOA_INDEX, and ZOD_INDEX.
Referenced by DoCalcRxPowerSpectralDensity().
CalLongTerm()
complexVector_t ns3::millicar::MmWaveVehicularSpectrumPropagationLossModel::CalLongTerm (Ptr< Params3gpp > params) const private
Compute and return the long term fading params in order to decrease the computational load.
Parameters
the channel realizationin as a Params3gpp object
Returns
the complexVector_t with the BF applied to the channel
Definition at line 517 of file mmwave-vehicular-spectrum-propagation-loss-model.cc.
Referenced by DoCalcRxPowerSpectralDensity().
DeleteChannel()
void ns3::millicar::MmWaveVehicularSpectrumPropagationLossModel::DeleteChannel (Ptr< const MobilityModel > a, Ptr< const MobilityModel > b) const private
Delete the m_channel entry associated to the Params3gpp object of pair (a,b) but keep the other parameters, so that the spatial consistency procedure can be used.
Parameters
the mobility model of the transmitter
the mobility model of the receiver
Definition at line 776 of file mmwave-vehicular-spectrum-propagation-loss-model.cc.
References m_channelMap.
Referenced by DoCalcRxPowerSpectralDensity().
DoCalcRxPowerSpectralDensity()
Ptr< SpectrumValue > ns3::millicar::MmWaveVehicularSpectrumPropagationLossModel::DoCalcRxPowerSpectralDensity (Ptr< const SpectrumValue > txPsd, Ptr< const MobilityModel > a, Ptr< const MobilityModel > b) const private
Inherited from SpectrumPropagationLossModel, it returns the PSD at the receiver.
Parameters
the transmitted PSD
the mobility model of the transmitter
the mobility model of the receiver
Returns
the received PSD
Definition at line 178 of file mmwave-vehicular-spectrum-propagation-loss-model.cc.
References CalBeamformingGain(), CalLongTerm(), DeleteChannel(), Get3gppTable(), GetNewChannel(), m_3gppPathloss, m_channelMap, m_deviceAntennaMap, m_frequency, m_o2i, m_updatePeriod, and UpdateChannel().
DoDispose()
void ns3::millicar::MmWaveVehicularSpectrumPropagationLossModel::DoDispose (void)
Definition at line 165 of file mmwave-vehicular-spectrum-propagation-loss-model.cc.
Get3gppTable()
Ptr< ParamsTable > ns3::millicar::MmWaveVehicularSpectrumPropagationLossModel::Get3gppTable (char condition, bool o2i, double hBS, double hUT, double distance2D) const private
Returns the ParamsTable with the parameters of TR 38.900 Table 7.5-6 that apply to a certain scenario.
Parameters
the channel condition
the o2i condition
the BS height (i.e., eNB)
the UT height (i.e., UE)
the 2D distance
Returns
the ParamsTable structure
Definition at line 547 of file mmwave-vehicular-spectrum-propagation-loss-model.cc.
References m_frequency, and m_scenario.
Referenced by DoCalcRxPowerSpectralDensity().
GetFrequency()
double ns3::millicar::MmWaveVehicularSpectrumPropagationLossModel::GetFrequency (void) const
Returns
the current frequency (Hz)
Definition at line 2492 of file mmwave-vehicular-spectrum-propagation-loss-model.cc.
References m_frequency.
Referenced by GetTypeId().
GetNewChannel()
Ptr< Params3gpp > ns3::millicar::MmWaveVehicularSpectrumPropagationLossModel::GetNewChannel (Ptr< ParamsTable > table3gpp, Vector locUT, char condition, bool o2i, Ptr< MmWaveVehicularAntennaArrayModel > txAntenna, Ptr< MmWaveVehicularAntennaArrayModel > rxAntenna, uint16_t * txAntennaNum, uint16_t * rxAntennaNum, Angles & rxAngle, Angles & txAngle, Vector speed, double dis2D, double dis3D) const private
Get a new realization of the channel.
Parameters
the ParamsTable for the specific scenario
the location of UT
the channel condition
the o2i condition
the ArrayAntennaModel for the txAntenna
the ArrayAntennaModel for the rxAntenna
the number of txAntenna per row
the number of rxAntenna per row
the rxAngle
the txAngle
the relative speed between tx and rx
the 2D distance between tx and rx
the 3D distance between tx and rx
Returns
the channel realization in a Params3gpp object
Definition at line 791 of file mmwave-vehicular-spectrum-propagation-loss-model.cc.
References CalAttenuationOfBlockage(), m_blockage, m_normalRv, and m_uniformRv.
Referenced by DoCalcRxPowerSpectralDensity().
GetOxygenLoss()
double ns3::millicar::MmWaveVehicularSpectrumPropagationLossModel::GetOxygenLoss (double frequency, double dist3D, double tau, double tauDelta) const private
Returns the loss associated to the oxygen absorption as described in p.
43 of TR 38.901
Returns
a double corresponding to the loss associated to the oxygen absorption
Parameters
frequency of the subcarrier
3D distance between the communicating terminals
delay associated to the cluster for which we are evaluating the loss
0 if in LOS condition and, if not, minimum delay among all clusters
Definition at line 474 of file mmwave-vehicular-spectrum-propagation-loss-model.cc.
Referenced by CalBeamformingGain().
GetSystemBandwidth()
double ns3::millicar::MmWaveVehicularSpectrumPropagationLossModel::GetSystemBandwidth () const private
Returns the bandwidth used in a scenario.
Returns
a double with the bandwidth
GetTypeId()
TypeId ns3::millicar::MmWaveVehicularSpectrumPropagationLossModel::GetTypeId (void) static
Definition at line 109 of file mmwave-vehicular-spectrum-propagation-loss-model.cc.
References GetFrequency(), m_blockage, m_blockerSpeed, m_numNonSelfBloking, m_o2i, m_oxygenAbsorption, m_portraitMode, m_updatePeriod, and SetFrequency().
SetFrequency()
void ns3::millicar::MmWaveVehicularSpectrumPropagationLossModel::SetFrequency (double freq)
Parameters
freq the operating frequency (Hz)
Definition at line 2486 of file mmwave-vehicular-spectrum-propagation-loss-model.cc.
References m_frequency.
Referenced by GetTypeId().
SetPathlossModel()
void ns3::millicar::MmWaveVehicularSpectrumPropagationLossModel::SetPathlossModel (Ptr< PropagationLossModel > pathloss)
Set the pathloss model associated to this class.
Parameters
a pointer to the pathloss model, which has to implement the PropagationLossModel interface
Definition at line 498 of file mmwave-vehicular-spectrum-propagation-loss-model.cc.
References m_3gppPathloss, and m_scenario.
UpdateChannel()
Ptr< Params3gpp > ns3::millicar::MmWaveVehicularSpectrumPropagationLossModel::UpdateChannel (Ptr< Params3gpp > params3gpp, Ptr< ParamsTable > table3gpp, Ptr< MmWaveVehicularAntennaArrayModel > txAntenna, Ptr< MmWaveVehicularAntennaArrayModel > rxAntenna, uint16_t * txAntennaNum, uint16_t * rxAntennaNum, Angles & rxAngle, Angles & txAngle) const private
Update the channel realization with procedure A of TR 38.900 Sec 7.6.3.2 for the spatial consistency.
Parameters
the previous channel realization in a Params3gpp object
the ParamsTable for the specific scenario
the ArrayAntennaModel for the txAntenna
the ArrayAntennaModel for the rxAntenna
the number of txAntenna per row
the number of rxAntenna per row
the rxAngle
the txAngle
Returns
the channel realization in a Params3gpp object
Definition at line 1632 of file mmwave-vehicular-spectrum-propagation-loss-model.cc.
References AOA_INDEX, AOD_INDEX, CalAttenuationOfBlockage(), m_blockage, m_normalRv, m_updatePeriod, ZOA_INDEX, and ZOD_INDEX.
Referenced by DoCalcRxPowerSpectralDensity().
Member Data Documentation
m_3gppPathloss
Ptr<PropagationLossModel> ns3::millicar::MmWaveVehicularSpectrumPropagationLossModel::m_3gppPathloss private
Definition at line 344 of file mmwave-vehicular-spectrum-propagation-loss-model.h.
Referenced by DoCalcRxPowerSpectralDensity(), and SetPathlossModel().
m_blockage
bool ns3::millicar::MmWaveVehicularSpectrumPropagationLossModel::m_blockage private
Definition at line 347 of file mmwave-vehicular-spectrum-propagation-loss-model.h.
Referenced by GetNewChannel(), GetTypeId(), and UpdateChannel().
m_blockerSpeed
double ns3::millicar::MmWaveVehicularSpectrumPropagationLossModel::m_blockerSpeed private
Definition at line 352 of file mmwave-vehicular-spectrum-propagation-loss-model.h.
Referenced by CalAttenuationOfBlockage(), and GetTypeId().
m_channelMap
std::map< key_t, Ptr<Params3gpp> > ns3::millicar::MmWaveVehicularSpectrumPropagationLossModel::m_channelMap mutable private
Definition at line 332 of file mmwave-vehicular-spectrum-propagation-loss-model.h.
Referenced by DeleteChannel(), and DoCalcRxPowerSpectralDensity().
m_deviceAntennaMap
std::map< Ptr<NetDevice>, Ptr<MmWaveVehicularAntennaArrayModel> > ns3::millicar::MmWaveVehicularSpectrumPropagationLossModel::m_deviceAntennaMap private
Definition at line 356 of file mmwave-vehicular-spectrum-propagation-loss-model.h.
Referenced by AddDevice(), and DoCalcRxPowerSpectralDensity().
m_expRv
Ptr<ExponentialRandomVariable> ns3::millicar::MmWaveVehicularSpectrumPropagationLossModel::m_expRv private
Definition at line 342 of file mmwave-vehicular-spectrum-propagation-loss-model.h.
Referenced by MmWaveVehicularSpectrumPropagationLossModel().
m_frequency
double ns3::millicar::MmWaveVehicularSpectrumPropagationLossModel::m_frequency private
Definition at line 334 of file mmwave-vehicular-spectrum-propagation-loss-model.h.
Referenced by CalAttenuationOfBlockage(), CalBeamformingGain(), DoCalcRxPowerSpectralDensity(), Get3gppTable(), GetFrequency(), and SetFrequency().
m_interferenceOrDataMode
bool ns3::millicar::MmWaveVehicularSpectrumPropagationLossModel::m_interferenceOrDataMode private
Definition at line 353 of file mmwave-vehicular-spectrum-propagation-loss-model.h.
m_normalRv
Ptr<NormalRandomVariable> ns3::millicar::MmWaveVehicularSpectrumPropagationLossModel::m_normalRv private
Definition at line 339 of file mmwave-vehicular-spectrum-propagation-loss-model.h.
Referenced by GetNewChannel(), MmWaveVehicularSpectrumPropagationLossModel(), and UpdateChannel().
m_normalRvBlockage
Ptr<NormalRandomVariable> ns3::millicar::MmWaveVehicularSpectrumPropagationLossModel::m_normalRvBlockage private
Definition at line 340 of file mmwave-vehicular-spectrum-propagation-loss-model.h.
Referenced by CalAttenuationOfBlockage(), and MmWaveVehicularSpectrumPropagationLossModel().
m_numNonSelfBloking
uint16_t ns3::millicar::MmWaveVehicularSpectrumPropagationLossModel::m_numNonSelfBloking private
Definition at line 348 of file mmwave-vehicular-spectrum-propagation-loss-model.h.
Referenced by CalAttenuationOfBlockage(), and GetTypeId().
m_o2i
bool ns3::millicar::MmWaveVehicularSpectrumPropagationLossModel::m_o2i private
Definition at line 354 of file mmwave-vehicular-spectrum-propagation-loss-model.h.
Referenced by DoCalcRxPowerSpectralDensity(), and GetTypeId().
m_oxygenAbsorption
bool ns3::millicar::MmWaveVehicularSpectrumPropagationLossModel::m_oxygenAbsorption private
Definition at line 350 of file mmwave-vehicular-spectrum-propagation-loss-model.h.
Referenced by CalBeamformingGain(), and GetTypeId().
m_portraitMode
bool ns3::millicar::MmWaveVehicularSpectrumPropagationLossModel::m_portraitMode private
Definition at line 349 of file mmwave-vehicular-spectrum-propagation-loss-model.h.
Referenced by CalAttenuationOfBlockage(), and GetTypeId().
m_scenario
std::string ns3::millicar::MmWaveVehicularSpectrumPropagationLossModel::m_scenario private
Definition at line 351 of file mmwave-vehicular-spectrum-propagation-loss-model.h.
Referenced by CalAttenuationOfBlockage(), CalBeamformingGain(), Get3gppTable(), and SetPathlossModel().
m_table3gpp
Ptr<ParamsTable> ns3::millicar::MmWaveVehicularSpectrumPropagationLossModel::m_table3gpp private
Definition at line 345 of file mmwave-vehicular-spectrum-propagation-loss-model.h.
m_uniformRv
Ptr<UniformRandomVariable> ns3::millicar::MmWaveVehicularSpectrumPropagationLossModel::m_uniformRv private
Definition at line 336 of file mmwave-vehicular-spectrum-propagation-loss-model.h.
Referenced by CalBeamformingGain(), GetNewChannel(), and MmWaveVehicularSpectrumPropagationLossModel().
m_uniformRvBlockage
Ptr<UniformRandomVariable> ns3::millicar::MmWaveVehicularSpectrumPropagationLossModel::m_uniformRvBlockage private
Definition at line 337 of file mmwave-vehicular-spectrum-propagation-loss-model.h.
Referenced by CalAttenuationOfBlockage(), and MmWaveVehicularSpectrumPropagationLossModel().
m_updatePeriod
Time ns3::millicar::MmWaveVehicularSpectrumPropagationLossModel::m_updatePeriod private
Definition at line 346 of file mmwave-vehicular-spectrum-propagation-loss-model.h.
Referenced by DoCalcRxPowerSpectralDensity(), GetTypeId(), and UpdateChannel().
The documentation for this class was generated from the following files:
model/mmwave-vehicular-spectrum-propagation-loss-model.h
model/mmwave-vehicular-spectrum-propagation-loss-model.cc