MilliCar: ns3::millicar::MmWaveSidelinkPhy Class Reference
ns3::millicar::MmWaveSidelinkPhy Class Reference
#include "mmwave-sidelink-phy.h"
Public Member Functions
MmWaveSidelinkPhy ()
Dummy constructor, it is not used.
MmWaveSidelinkPhy (Ptr< MmWaveSidelinkSpectrumPhy > spectrumPhy, Ptr< mmwave::MmWavePhyMacCommon > confParams)
MmWaveSidelinkPhy real constructor.
virtual ~MmWaveSidelinkPhy ()
Desctructor.
void AddDevice (uint64_t rnti, Ptr< NetDevice > dev)
Add a <rnti, device> pair to m_deviceMap.
void DoAddTransportBlock (Ptr< PacketBurst > pb, mmwave::TtiAllocInfo info)
Add a transport block to the transmission buffer, which will be sent in the current slot.
virtual void DoDispose (void)
virtual void DoInitialize (void)
void DoPrepareForReceptionFrom (uint16_t rnti)
Prepare for the reception from another device by properly configuring the beamforming vector.
void GenerateSinrReport (const SpectrumValue &sinr, uint16_t rnti, uint8_t numSym, uint32_t tbSize, uint8_t mcs)
This method generates a new SINR report and sends it to the MAC layer.
Ptr< mmwave::MmWavePhyMacCommon > GetConfigurationParameters (void) const
Returns the mmwave::MmWavePhyMacCommon instance associated with this phy containing the configuration parameters.
double GetNoiseFigure () const
Returns the noise figure.
MmWaveSidelinkPhySapProvider * GetPhySapProvider () const
Get the PHY SAP provider.
Ptr< MmWaveSidelinkSpectrumPhy > GetSpectrumPhy () const
Returns the SpectrumPhy instance associated with this phy.
double GetTxPower () const
Returns the tx power.
void Receive (Ptr< Packet > p)
Receive the packet from SpectrumPhy and forward it up to the MAC.
void SetNoiseFigure (double pf)
Set the noise figure.
void SetPhySapUser (MmWaveSidelinkPhySapUser *sap)
Set the PHY SAP user.
void SetTxPower (double power)
Set the tx power.
Static Public Member Functions
static TypeId GetTypeId (void)
Private Types
typedef std::pair< Ptr< PacketBurst >, mmwave::TtiAllocInfo > PhyBufferEntry
type of the phy buffer entries
Private Member Functions
void SendDataChannels (Ptr< PacketBurst > pb, Time duration, mmwave::TtiAllocInfo info, std::vector< int > rbBitmap)
Send the packet burts.
std::vector< int > SetSubChannelsForTransmission ()
Set the transmission mask and creates the power spectral density for the transmission.
uint8_t SlData (Ptr< PacketBurst > pb, mmwave::TtiAllocInfo info)
Transmit a transport block.
void StartSlot (mmwave::SfnSf timingInfo)
Start a slot.
mmwave::SfnSf UpdateTimingInfo (mmwave::SfnSf info) const
TODO: this can be done by overloading the operator ++ of the mmwave::SfnSf struct Update the mmwave::SfnSf structure to point to the next slot.
Private Attributes
std::map< uint64_t, Ptr< NetDevice > > m_deviceMap
map containing the <rnti, device> pairs of the nodes we want to communicate with
double m_noiseFigure
the noise figure in dB
std::list< PhyBufferEntry > m_phyBuffer
buffer of transport blocks to send in the current slot
Ptr< mmwave::MmWavePhyMacCommon > m_phyMacConfig
the configuration parameters
MmWaveSidelinkPhySapProvider * m_phySapProvider
Sidelink PHY SAP provider.
MmWaveSidelinkPhySapUser * m_phySapUser
Sidelink PHY SAP user.
Ptr< MmWaveSidelinkSpectrumPhy > m_sidelinkSpectrumPhy
the SpectrumPhy instance associated with this PHY
double m_txPower
the transmission power in dBm
Detailed Description
Definition at line 31 of file mmwave-sidelink-phy.h.
Member Typedef Documentation
PhyBufferEntry
typedef std::pair<Ptr<PacketBurst>, mmwave::TtiAllocInfo> ns3::millicar::MmWaveSidelinkPhy::PhyBufferEntry private
type of the phy buffer entries
Definition at line 204 of file mmwave-sidelink-phy.h.
Constructor & Destructor Documentation
MmWaveSidelinkPhy() [1/2]
ns3::millicar::MmWaveSidelinkPhy::MmWaveSidelinkPhy ()
Dummy constructor, it is not used.
Definition at line 56 of file mmwave-sidelink-phy.cc.
MmWaveSidelinkPhy() [2/2]
ns3::millicar::MmWaveSidelinkPhy::MmWaveSidelinkPhy (Ptr< MmWaveSidelinkSpectrumPhy > spectrumPhy, Ptr< mmwave::MmWavePhyMacCommon > confParams)
MmWaveSidelinkPhy real constructor.
Parameters
channelPhy spectrum phy
confParams instance of mmwave::MmWavePhyMacCommon containing the configuration parameters
Usually called by the helper. It starts the event loop for the device.
Definition at line 62 of file mmwave-sidelink-phy.cc.
References ns3::millicar::MacSidelinkMemberPhySapProvider::MacSidelinkMemberPhySapProvider(), and StartSlot().
~MmWaveSidelinkPhy()
ns3::millicar::MmWaveSidelinkPhy::~MmWaveSidelinkPhy () virtual
Desctructor.
Definition at line 79 of file mmwave-sidelink-phy.cc.
Member Function Documentation
AddDevice()
void ns3::millicar::MmWaveSidelinkPhy::AddDevice (uint64_t rnti, Ptr< NetDevice > dev)
Add a <rnti, device> pair to m_deviceMap.
All the devices we want to communicate with must be inserted in this map, otherwise we would not be able to correctly configure the beamforming.
Parameters
rnti the RNTI identifier
dev pointer to the NetDevice object
Definition at line 330 of file mmwave-sidelink-phy.cc.
DoAddTransportBlock()
void ns3::millicar::MmWaveSidelinkPhy::DoAddTransportBlock (Ptr< PacketBurst > pb, mmwave::TtiAllocInfo info)
Add a transport block to the transmission buffer, which will be sent in the current slot.
Parameters
pb the packet burst containing the packets to be sent
info the mmwave::TtiAllocInfo instance containg the transmission information
Definition at line 178 of file mmwave-sidelink-phy.cc.
DoDispose()
void ns3::millicar::MmWaveSidelinkPhy::DoDispose (void) virtual
Definition at line 118 of file mmwave-sidelink-phy.cc.
DoInitialize()
void ns3::millicar::MmWaveSidelinkPhy::DoInitialize (void) virtual
Definition at line 112 of file mmwave-sidelink-phy.cc.
DoPrepareForReceptionFrom()
void ns3::millicar::MmWaveSidelinkPhy::DoPrepareForReceptionFrom (uint16_t rnti)
Prepare for the reception from another device by properly configuring the beamforming vector.
Parameters
rnti the RNTI of the transmitting device
Definition at line 322 of file mmwave-sidelink-phy.cc.
GenerateSinrReport()
void ns3::millicar::MmWaveSidelinkPhy::GenerateSinrReport (const SpectrumValue & sinr, uint16_t rnti, uint8_t numSym, uint32_t tbSize, uint8_t mcs)
This method generates a new SINR report and sends it to the MAC layer.
It is hooked to the callback MmWaveSidelinkSpectrumPhy::m_slSinrReportCallback
Parameters
sinr pointer to the SpectrumValue instance representing the SINR measured on all the spectrum chunks
rnti the RNTI of the tranmitting device
numSym size of the transport block that generated the report in number of OFDM symbols
tbSize size of the transport block that generated the report in bytes
mcs the MCS of the transmission
Definition at line 354 of file mmwave-sidelink-phy.cc.
Referenced by ns3::millicar::MmWaveVehicularHelper::InstallSingleMmWaveVehicularNetDevice().
GetConfigurationParameters()
Ptr< mmwave::MmWavePhyMacCommon > ns3::millicar::MmWaveSidelinkPhy::GetConfigurationParameters (void) const
Returns the mmwave::MmWavePhyMacCommon instance associated with this phy containing the configuration parameters.
Returns
the mmwave::MmWavePhyMacCommon instance
Definition at line 158 of file mmwave-sidelink-phy.cc.
GetNoiseFigure()
double ns3::millicar::MmWaveSidelinkPhy::GetNoiseFigure () const
Returns the noise figure.
Returns
the noise figure in dB
Definition at line 146 of file mmwave-sidelink-phy.cc.
Referenced by GetTypeId().
GetPhySapProvider()
MmWaveSidelinkPhySapProvider * ns3::millicar::MmWaveSidelinkPhy::GetPhySapProvider () const
Get the PHY SAP provider.
Returns
a pointer to the SAP provider to the MAC
Definition at line 164 of file mmwave-sidelink-phy.cc.
GetSpectrumPhy()
Ptr< MmWaveSidelinkSpectrumPhy > ns3::millicar::MmWaveSidelinkPhy::GetSpectrumPhy () const
Returns the SpectrumPhy instance associated with this phy.
Returns
the SpectrumPhy instance
Definition at line 152 of file mmwave-sidelink-phy.cc.
GetTxPower()
double ns3::millicar::MmWaveSidelinkPhy::GetTxPower () const
Returns the tx power.
Returns
the tx power in dBm
Definition at line 130 of file mmwave-sidelink-phy.cc.
Referenced by GetTypeId().
GetTypeId()
TypeId ns3::millicar::MmWaveSidelinkPhy::GetTypeId (void) static
Definition at line 85 of file mmwave-sidelink-phy.cc.
References GetNoiseFigure(), GetTxPower(), SetNoiseFigure(), and SetTxPower().
Receive()
void ns3::millicar::MmWaveSidelinkPhy::Receive (Ptr< Packet > p)
Receive the packet from SpectrumPhy and forward it up to the MAC.
Parameters
p received packet
Definition at line 345 of file mmwave-sidelink-phy.cc.
Referenced by ns3::millicar::MmWaveVehicularHelper::InstallSingleMmWaveVehicularNetDevice().
SendDataChannels()
void ns3::millicar::MmWaveSidelinkPhy::SendDataChannels (Ptr< PacketBurst > pb, Time duration, mmwave::TtiAllocInfo info, std::vector< int > rbBitmap) private
Send the packet burts.
Parameters
pb the packet burst
duration the duration of the transmissin
info the mmwave::TtiAllocInfo instance containg the transmission information
rbBitmap the mask indicating the suchannels to be used for the transmission
Definition at line 259 of file mmwave-sidelink-phy.cc.
Referenced by SlData().
SetNoiseFigure()
void ns3::millicar::MmWaveSidelinkPhy::SetNoiseFigure (double pf)
Set the noise figure.
Parameters
the noise figure in dB
Definition at line 136 of file mmwave-sidelink-phy.cc.
Referenced by GetTypeId().
SetPhySapUser()
void ns3::millicar::MmWaveSidelinkPhy::SetPhySapUser (MmWaveSidelinkPhySapUser * sap)
Set the PHY SAP user.
Parameters
sap the PHY SAP user
Definition at line 171 of file mmwave-sidelink-phy.cc.
SetSubChannelsForTransmission()
std::vector< int > ns3::millicar::MmWaveSidelinkPhy::SetSubChannelsForTransmission () private
Set the transmission mask and creates the power spectral density for the transmission.
Returns
mask indicating the suchannels used for the transmission
Definition at line 274 of file mmwave-sidelink-phy.cc.
SetTxPower()
void ns3::millicar::MmWaveSidelinkPhy::SetTxPower (double power)
Set the tx power.
Parameters
the tx power in dBm
Definition at line 125 of file mmwave-sidelink-phy.cc.
Referenced by GetTypeId().
SlData()
uint8_t ns3::millicar::MmWaveSidelinkPhy::SlData (Ptr< PacketBurst > pb, mmwave::TtiAllocInfo info) private
Transmit a transport block.
Parameters
pb the packet burst containing the packets to be sent
info the mmwave::TtiAllocInfo instance containg the transmission information
Returns
the number of symbols used to send this TB
Definition at line 231 of file mmwave-sidelink-phy.cc.
References SendDataChannels().
StartSlot()
void ns3::millicar::MmWaveSidelinkPhy::StartSlot (mmwave::SfnSf timingInfo) private
Start a slot.
Send all the transport blocks in the buffer.
Parameters
timingInfo the structure containing the timing information
Definition at line 188 of file mmwave-sidelink-phy.cc.
Referenced by MmWaveSidelinkPhy().
UpdateTimingInfo()
mmwave::SfnSf ns3::millicar::MmWaveSidelinkPhy::UpdateTimingInfo (mmwave::SfnSf info) const private
TODO: this can be done by overloading the operator ++ of the mmwave::SfnSf struct Update the mmwave::SfnSf structure to point to the next slot.
If the current slot the last slot of the subframe, the next slot index will be 0 and the subframe index will be incremented. If the current subframe is the last subframe of the frame, the next subframe index will be 0 and the frame frame index will be incremented.
Parameters
info the mmwave::SfnSf structure containg frame, subframe and slot indeces
Returns
the updated SnfSn structure pointing to the next slot
Definition at line 293 of file mmwave-sidelink-phy.cc.
Member Data Documentation
m_deviceMap
std::map<uint64_t, Ptr<NetDevice> > ns3::millicar::MmWaveSidelinkPhy::m_deviceMap private
map containing the <rnti, device> pairs of the nodes we want to communicate with
Definition at line 206 of file mmwave-sidelink-phy.h.
m_noiseFigure
double ns3::millicar::MmWaveSidelinkPhy::m_noiseFigure private
the noise figure in dB
Definition at line 201 of file mmwave-sidelink-phy.h.
m_phyBuffer
std::list<PhyBufferEntry> ns3::millicar::MmWaveSidelinkPhy::m_phyBuffer private
buffer of transport blocks to send in the current slot
Definition at line 205 of file mmwave-sidelink-phy.h.
m_phyMacConfig
Ptr<mmwave::MmWavePhyMacCommon> ns3::millicar::MmWaveSidelinkPhy::m_phyMacConfig private
the configuration parameters
Definition at line 203 of file mmwave-sidelink-phy.h.
m_phySapProvider
MmWaveSidelinkPhySapProvider* ns3::millicar::MmWaveSidelinkPhy::m_phySapProvider private
Sidelink PHY SAP provider.
Definition at line 199 of file mmwave-sidelink-phy.h.
m_phySapUser
MmWaveSidelinkPhySapUser* ns3::millicar::MmWaveSidelinkPhy::m_phySapUser private
Sidelink PHY SAP user.
Definition at line 198 of file mmwave-sidelink-phy.h.
m_sidelinkSpectrumPhy
Ptr<MmWaveSidelinkSpectrumPhy> ns3::millicar::MmWaveSidelinkPhy::m_sidelinkSpectrumPhy private
the SpectrumPhy instance associated with this PHY
Definition at line 202 of file mmwave-sidelink-phy.h.
m_txPower
double ns3::millicar::MmWaveSidelinkPhy::m_txPower private
the transmission power in dBm
Definition at line 200 of file mmwave-sidelink-phy.h.
The documentation for this class was generated from the following files:
model/mmwave-sidelink-phy.h
model/mmwave-sidelink-phy.cc