MilliCar: MmWaveVehicularSpectrumPhyTestCase1 Class Reference
MmWaveVehicularSpectrumPhyTestCase1 Class Reference
This is a test to check if the class MmWaveSidelinkSpectrumPhy correctly computes the SNR.
Public Member Functions
MmWaveVehicularSpectrumPhyTestCase1 ()
Constructor.
virtual ~MmWaveVehicularSpectrumPhyTestCase1 ()
Destructor.
Private Member Functions
virtual void DoRun (void)
This method run the test.
void Rx (Ptr< Packet > p)
This method is a callback sink which is fired when the rx receives a packet.
void StartTest (double dist)
This method runs the simulation using the specified distance between the devices.
void UpdateSinrPerceived (const SpectrumValue &sinr)
This method is a callback sink which is fired when the rx updates the SINR estimate.
Private Attributes
double m_expectedSinr
expected average SINR
Detailed Description
This is a test to check if the class MmWaveSidelinkSpectrumPhy correctly computes the SNR.
Definition at line 37 of file mmwave-vehicular-spectrum-phy-test.cc.
Constructor & Destructor Documentation
MmWaveVehicularSpectrumPhyTestCase1()
MmWaveVehicularSpectrumPhyTestCase1::MmWaveVehicularSpectrumPhyTestCase1 ()
Constructor.
Definition at line 79 of file mmwave-vehicular-spectrum-phy-test.cc.
~MmWaveVehicularSpectrumPhyTestCase1()
MmWaveVehicularSpectrumPhyTestCase1::~MmWaveVehicularSpectrumPhyTestCase1 () virtual
Destructor.
Definition at line 84 of file mmwave-vehicular-spectrum-phy-test.cc.
Member Function Documentation
DoRun()
void MmWaveVehicularSpectrumPhyTestCase1::DoRun (void) private virtual
This method run the test.
Definition at line 103 of file mmwave-vehicular-spectrum-phy-test.cc.
References StartTest().
Rx()
void MmWaveVehicularSpectrumPhyTestCase1::Rx (Ptr< Packet > p) private
This method is a callback sink which is fired when the rx receives a packet.
Parameters
p received packet
Definition at line 89 of file mmwave-vehicular-spectrum-phy-test.cc.
Referenced by StartTest().
StartTest()
void MmWaveVehicularSpectrumPhyTestCase1::StartTest (double dist) private
This method runs the simulation using the specified distance between the devices.
Parameters
dist inter-device distance
Definition at line 115 of file mmwave-vehicular-spectrum-phy-test.cc.
References m_expectedSinr, Rx(), and UpdateSinrPerceived().
Referenced by DoRun().
UpdateSinrPerceived()
void MmWaveVehicularSpectrumPhyTestCase1::UpdateSinrPerceived (const SpectrumValue & sinr) private
This method is a callback sink which is fired when the rx updates the SINR estimate.
Parameters
sinr the sinr value
Definition at line 95 of file mmwave-vehicular-spectrum-phy-test.cc.
References m_expectedSinr.
Referenced by StartTest().
Member Data Documentation
m_expectedSinr
double MmWaveVehicularSpectrumPhyTestCase1::m_expectedSinr private
expected average SINR
Definition at line 76 of file mmwave-vehicular-spectrum-phy-test.cc.
Referenced by StartTest(), and UpdateSinrPerceived().
The documentation for this class was generated from the following file:
test/mmwave-vehicular-spectrum-phy-test.cc