MilliCar: MmWaveVehicularInterferenceTestCase Class Reference
MmWaveVehicularInterferenceTestCase Class Reference
The aim of this test is to check whether the interference was evaluated correctly when different groups of nodes are transmitting in the same slot, sharing the same cell.
Public Member Functions
MmWaveVehicularInterferenceTestCase ()
Constructor.
virtual ~MmWaveVehicularInterferenceTestCase ()
Destructor.
virtual void DoRun (void)
This method run the test.
void StartTest (double txPower)
Private Member Functions
void CheckSinrPerceivedG1 (const SpectrumValue &sinr)
Callback sink to keep track of the SINR evaluated by the devices associated to GROUP 1.
void CheckSinrPerceivedG2 (const SpectrumValue &sinr)
Callback sink to keep track of the SINR evaluated by the devices associated to GROUP 2.
Private Attributes
double g_expectedSinrG1
SINR expected in GROUP 1.
double g_expectedSinrG2
SINR expected in GROUP 2.
Detailed Description
The aim of this test is to check whether the interference was evaluated correctly when different groups of nodes are transmitting in the same slot, sharing the same cell.
Communication is done using an ideal channel; for this reason, the position of the vehicles does not influence the results. It has been specified just for the sake of giving context to the example.
Definition at line 45 of file mmwave-vehicular-interference-test.cc.
Constructor & Destructor Documentation
MmWaveVehicularInterferenceTestCase()
MmWaveVehicularInterferenceTestCase::MmWaveVehicularInterferenceTestCase ()
Constructor.
Definition at line 84 of file mmwave-vehicular-interference-test.cc.
~MmWaveVehicularInterferenceTestCase()
MmWaveVehicularInterferenceTestCase::~MmWaveVehicularInterferenceTestCase () virtual
Destructor.
Definition at line 89 of file mmwave-vehicular-interference-test.cc.
Member Function Documentation
CheckSinrPerceivedG1()
void MmWaveVehicularInterferenceTestCase::CheckSinrPerceivedG1 (const SpectrumValue & sinr) private
Callback sink to keep track of the SINR evaluated by the devices associated to GROUP 1.
Parameters
sinr SpectrumValue corresponding to the evaluated SINR
Definition at line 94 of file mmwave-vehicular-interference-test.cc.
References g_expectedSinrG1.
Referenced by StartTest().
CheckSinrPerceivedG2()
void MmWaveVehicularInterferenceTestCase::CheckSinrPerceivedG2 (const SpectrumValue & sinr) private
Callback sink to keep track of the SINR evaluated by the devices associated to GROUP 2.
Parameters
sinr SpectrumValue corresponding to the evaluated SINR
Definition at line 103 of file mmwave-vehicular-interference-test.cc.
References g_expectedSinrG2.
Referenced by StartTest().
DoRun()
void MmWaveVehicularInterferenceTestCase::DoRun (void) virtual
This method run the test.
Definition at line 112 of file mmwave-vehicular-interference-test.cc.
References g_expectedSinrG1, g_expectedSinrG2, and StartTest().
StartTest()
void MmWaveVehicularInterferenceTestCase::StartTest (double txPower)
Definition at line 132 of file mmwave-vehicular-interference-test.cc.
References CheckSinrPerceivedG1(), CheckSinrPerceivedG2(), g_expectedSinrG1, and g_expectedSinrG2.
Referenced by DoRun().
Member Data Documentation
g_expectedSinrG1
double MmWaveVehicularInterferenceTestCase::g_expectedSinrG1 private
SINR expected in GROUP 1.
Definition at line 79 of file mmwave-vehicular-interference-test.cc.
Referenced by CheckSinrPerceivedG1(), DoRun(), and StartTest().
g_expectedSinrG2
double MmWaveVehicularInterferenceTestCase::g_expectedSinrG2 private
SINR expected in GROUP 2.
Definition at line 80 of file mmwave-vehicular-interference-test.cc.
Referenced by CheckSinrPerceivedG2(), DoRun(), and StartTest().
The documentation for this class was generated from the following file:
test/mmwave-vehicular-interference-test.cc