# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('mmwave-vehicular-example', ['mmwave-vehicular'])
    obj.source = 'mmwave-vehicular-example.cc'

