# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):

    obj = bld.create_ns3_program('mmwave-vehicular-example', ['mmwave-vehicular','core', 'propagation', 'spectrum', 'mmwave'])
    obj.source = 'mmwave-vehicular-example.cc'

    obj = bld.create_ns3_program('vehicular-simple-one', ['mmwave-vehicular','core', 'propagation', 'spectrum', 'mmwave'])
    obj.source = 'vehicular-simple-one.cc'

    obj = bld.create_ns3_program('vehicular-simple-two', ['mmwave-vehicular','core', 'propagation', 'spectrum', 'mmwave'])
    obj.source = 'vehicular-simple-two.cc'

    obj = bld.create_ns3_program('vehicular-simple-three', ['mmwave-vehicular','core', 'propagation', 'spectrum', 'mmwave'])
    obj.source = 'vehicular-simple-three.cc'

    obj = bld.create_ns3_program('mmwave-vehicular-link-adaptation-example', ['mmwave-vehicular'])
    obj.source = 'mmwave-vehicular-link-adaptation-example.cc'
